name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter (v3.22.1)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'  # ✅ includes Dart 3.8.1

      - name: Verify versions
        run: |
          flutter --version
          dart --version

      - name: Disable Flutter CLI animations & analytics
        run: |
          flutter config --no-analytics
          flutter config --no-cli-animations

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Build Web
        run: flutter build web
